### ISSUE TITLE
how do i use this

### ISSUE THREAD

**Issue by EzioisAwesome56** [VelocityPowered/bungeequack#1]
trying to put a bungeecord plugin in the plugins folder makes velocity not load it due to a missing version file

**Comment by astei** [comment]
BungeeQuack does not support the BungeeCord API. This point is made explicit on the [forum post](https://forums.velocitypowered.com/t/bungeequack-use-the-plugins-you-love-with-velocity/14):

> If you did not need to install a plugin on your BungeeCord server, it is very likely to work with BungeeQuack. However, **BungeeQuack does not and can not emulate the BungeeCord plugin API on Velocity**. We strongly suggest finding alternative plugins that are compatible with Velocity.

It's also reiterated in the README:

> BungeeQuack _does not_ intend to support the BungeeCord API. We wish to encourage the growth of Velocity-native plugins in our ecosystem.

The solution is simple: you must find a port of the plugin or find an alternative for it (much more difficult, to be fair, given that Velocity has been around for only four months).
